rule:
    input:
        render = 'programming.pdf'

subworkflow data:
    workdir: '../data'

rule render_rmarkdown:
    input:
        rmd  = 'programming.Rmd',
        data = ancient('survey_data.tsv')
    output:
        'programming.{ext}'
    wildcard_constraints:
        ext = '(?:pdf)'
    shell:
        '''Rscript -e "rmarkdown::render('{input.rmd}', output_format = '{wildcards.ext}_document')"'''

rule survey_data:
    input:
        data('survey_data.tsv')
    output:
        'survey_data.tsv'
    shell:
        'ln -sr {input:q} {output:q}'
